# Generated by Django 4.2 on 2026-02-23 05:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('dean', 'Dean'), ('head', 'Head'), ('coordinator', 'Coordinator'), ('staff', 'Staff')], max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='academic_staff_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='academic_staff', to='attendance.program')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='academic_staff', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Academic Staff',
                'db_table': 'academic_staff',
            },
        ),
    ]
