# Generated by Django 4.2 on 2026-02-23 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='liveness_verified',
            field=models.BooleanField(default=False, help_text='Verified that person is live via blink detection'),
        ),
    ]
