# Generated by Django 4.2 on 2026-02-23 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_attendance_liveness_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='liveness_verified',
            field=models.BooleanField(default=False),
        ),
    ]
