# Generated by Django 4.2 on 2026-02-23 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0006_student_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbsenceExcuse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('absence_date', models.DateField()),
                ('reason', models.TextField(help_text='Reason for absence', max_length=500)),
                ('proof_image', models.ImageField(help_text='Photo proof for your excuse', upload_to='absence_proofs/')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved (Excused)'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('remarks', models.TextField(blank=True, help_text="Dean's remarks", null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendance', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='excuse', to='attendance.attendance')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_excuses', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absence_excuses', to='attendance.student')),
            ],
            options={
                'verbose_name_plural': 'Absence Excuses',
                'db_table': 'absence_excuse',
                'ordering': ['-submitted_at'],
                'unique_together': {('student', 'absence_date')},
            },
        ),
    ]
