# Generated by Django 4.2 on 2026-02-23 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_absenceexcuse'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='proof_image',
            field=models.ImageField(blank=True, null=True, upload_to='leave_proofs/'),
        ),
        migrations.DeleteModel(
            name='AbsenceExcuse',
        ),
    ]
