# Generated by Django 4.2 on 2026-02-24 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_alter_student_address_alter_student_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='was_late',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('late', 'Late'), ('undertime', 'Undertime'), ('absent', 'Absent'), ('excused', 'Excused')], default='present', max_length=20),
        ),
    ]
