# Generated by Django 4.2 on 2026-02-28 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_studentdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='emergency_contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
