# Generated by Django 4.2 on 2026-02-28 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_student_emergency_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='emergency_contact_number',
            field=models.CharField(blank=True, help_text='Emergency contact phone number', max_length=20, null=True),
        ),
    ]
