# Generated by Django 4.2 on 2026-03-10 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0013_alter_student_emergency_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='emergency_contact_name',
            field=models.CharField(blank=True, help_text='Name of the emergency contact person', max_length=100, null=True),
        ),
    ]
